import { chromium } from 'playwright';
const BASE = 'http://localhost:3000';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await p.goto(`${BASE}/login`, { waitUntil: 'domcontentloaded', timeout: 60000 });
await p.waitForTimeout(2200);
await p.click('text=Chế độ Tập luyện').catch(() => {});
await p.waitForTimeout(400);
await p.fill('#login-email', 'admin@jamahome.vn');
await p.fill('#login-password', 'demo123');
await p.click('button[type=submit]');
await p.waitForTimeout(3200);
const d = p.locator('button:has-text("Bỏ qua")').first();
if (await d.isVisible().catch(() => false)) await d.click().catch(() => {});
await p.goto(`${BASE}/hr`, { waitUntil: 'domcontentloaded' }); await p.waitForTimeout(2500);
await p.locator('button:has-text("Cho nghỉ việc")').first().click();
await p.waitForTimeout(1800);
const modal = await p.locator('.fixed.inset-0').last().innerText().catch(() => '(không thấy modal)');
console.log('MODAL:', modal.replace(/\n+/g, ' | ').slice(0, 500));
await b.close();
