"""baseline full schema

Revision ID: ac9de03e7289
Revises: 
Create Date: 2026-07-15 00:57:52.081865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9de03e7289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('commission_type', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index('ix_feedbacks_status', ['status'], unique=False)
        batch_op.create_index('ix_feedbacks_user', ['user_id'], unique=False)

    op.create_table('fixed_costs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity_in_stock', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_category', ['category'], unique=False)
        batch_op.create_index('ix_materials_name', ['name'], unique=False)

    op.create_table('price_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('price_basic', sa.Float(), nullable=False),
    sa.Column('price_standard', sa.Float(), nullable=False),
    sa.Column('price_premium', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('price_items', schema=None) as batch_op:
        batch_op.create_index('ix_price_items_category', ['category', 'is_active'], unique=False)

    op.create_table('salary_grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grade_name', sa.String(length=100), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('bhxh_rate', sa.Float(), nullable=False),
    sa.Column('bhxh_company_rate', sa.Float(), nullable=False),
    sa.Column('bhyt_rate', sa.Float(), nullable=False),
    sa.Column('bhtn_rate', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('leader_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # FK teams.leader_id -> users.id được thêm SAU khi bảng users tồn tại (vòng tham chiếu teams <-> users)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resign_date', sa.DateTime(), nullable=True),
    sa.Column('resigned_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_role_dept', ['role', 'department'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_teams_leader_id_users', 'users', ['leader_id'], ['id'])

    op.create_table('variable_costs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('needs', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('property_type', sa.String(length=20), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('estimated_budget', sa.Float(), nullable=True),
    sa.Column('contact_status', sa.String(length=20), nullable=True),
    sa.Column('survey_date', sa.DateTime(), nullable=True),
    sa.Column('survey_photos', sa.Text(), nullable=True),
    sa.Column('property_class', sa.String(length=20), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('design_contract_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_assigned_stage', ['assigned_to', 'stage'], unique=False)
        batch_op.create_index('ix_leads_created', ['created_at'], unique=False)
        batch_op.create_index('ix_leads_priority_stage', ['priority', 'stage'], unique=False)
        batch_op.create_index('ix_leads_source_stage', ['source', 'stage'], unique=False)
        batch_op.create_index('ix_leads_stage_created', ['stage', 'created_at'], unique=False)
        batch_op.create_index('ix_leads_team_stage', ['team_id', 'stage'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_dedupe', ['user_id', 'type', 'ref_id', 'read'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read', 'created_at'], unique=False)

    op.create_table('payrolls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('commission_total', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.create_index('ix_payrolls_period', ['period'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_lead', ['lead_id', 'created_at'], unique=False)
        batch_op.create_index('ix_activities_user', ['user_id', 'created_at'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('tax_code', sa.String(length=30), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_name', ['name'], unique=False)
        batch_op.create_index('ix_customers_type', ['type'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('project_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('design_value', sa.Float(), nullable=True),
    sa.Column('construction_value', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.String(length=36), nullable=True),
    sa.Column('designer_id', sa.String(length=36), nullable=True),
    sa.Column('sales_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('target_end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sales_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_created', ['created_at'], unique=False)
        batch_op.create_index('ix_projects_pm', ['pm_id', 'status'], unique=False)
        batch_op.create_index('ix_projects_stage_status', ['stage', 'status'], unique=False)
        batch_op.create_index('ix_projects_status', ['status'], unique=False)

    op.create_table('commissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('milestone', sa.String(length=30), nullable=False),
    sa.Column('milestone_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_requests', schema=None) as batch_op:
        batch_op.create_index('ix_material_requests_project', ['project_id'], unique=False)
        batch_op.create_index('ix_material_requests_status', ['status'], unique=False)

    op.create_table('material_usages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price_at_use', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_usages', schema=None) as batch_op:
        batch_op.create_index('ix_material_usages_material', ['material_id'], unique=False)
        batch_op.create_index('ix_material_usages_project', ['project_id'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('erp_quotation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('ix_quotations_project', ['project_id'], unique=False)
        batch_op.create_index('ix_quotations_type_status', ['type', 'status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=True),
    sa.Column('final_file_url', sa.String(length=500), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_department', ['department'], unique=False)
        batch_op.create_index('ix_tasks_project_stage', ['project_id', 'stage'], unique=False)
        batch_op.create_index('ix_tasks_status', ['status'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_date', ['date'], unique=False)
        batch_op.create_index('ix_transactions_project', ['project_id', 'type'], unique=False)
        batch_op.create_index('ix_transactions_status', ['status'], unique=False)
        batch_op.create_index('ix_transactions_type', ['type'], unique=False)
        batch_op.create_index('ix_transactions_type_date', ['type', 'date'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.JSON(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('erp_contract_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contracts_project', ['project_id'], unique=False)
        batch_op.create_index('ix_contracts_status', ['status'], unique=False)

    op.create_table('task_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_activities', schema=None) as batch_op:
        batch_op.create_index('ix_task_activities_task', ['task_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Gỡ FK vòng teams -> users trước khi drop users
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_leader_id_users', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_activities', schema=None) as batch_op:
        batch_op.drop_index('ix_task_activities_task')

    op.drop_table('task_activities')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contracts_status')
        batch_op.drop_index('ix_contracts_project')

    op.drop_table('contracts')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_type_date')
        batch_op.drop_index('ix_transactions_type')
        batch_op.drop_index('ix_transactions_status')
        batch_op.drop_index('ix_transactions_project')
        batch_op.drop_index('ix_transactions_date')

    op.drop_table('transactions')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_status')
        batch_op.drop_index('ix_tasks_project_stage')
        batch_op.drop_index('ix_tasks_department')

    op.drop_table('tasks')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index('ix_quotations_type_status')
        batch_op.drop_index('ix_quotations_project')

    op.drop_table('quotations')
    with op.batch_alter_table('material_usages', schema=None) as batch_op:
        batch_op.drop_index('ix_material_usages_project')
        batch_op.drop_index('ix_material_usages_material')

    op.drop_table('material_usages')
    with op.batch_alter_table('material_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_material_requests_status')
        batch_op.drop_index('ix_material_requests_project')

    op.drop_table('material_requests')
    op.drop_table('commissions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_status')
        batch_op.drop_index('ix_projects_stage_status')
        batch_op.drop_index('ix_projects_pm')
        batch_op.drop_index('ix_projects_created')

    op.drop_table('projects')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_type')
        batch_op.drop_index('ix_customers_name')

    op.drop_table('customers')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_user')
        batch_op.drop_index('ix_activities_lead')

    op.drop_table('activities')
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_index('ix_payrolls_period')

    op.drop_table('payrolls')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index('ix_notifications_dedupe')

    op.drop_table('notifications')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_team_stage')
        batch_op.drop_index('ix_leads_stage_created')
        batch_op.drop_index('ix_leads_source_stage')
        batch_op.drop_index('ix_leads_priority_stage')
        batch_op.drop_index('ix_leads_created')
        batch_op.drop_index('ix_leads_assigned_stage')

    op.drop_table('leads')
    op.drop_table('variable_costs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_dept')

    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('system_settings')
    op.drop_table('salary_grades')
    with op.batch_alter_table('price_items', schema=None) as batch_op:
        batch_op.drop_index('ix_price_items_category')

    op.drop_table('price_items')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index('ix_materials_name')
        batch_op.drop_index('ix_materials_category')

    op.drop_table('materials')
    op.drop_table('fixed_costs')
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index('ix_feedbacks_user')
        batch_op.drop_index('ix_feedbacks_status')

    op.drop_table('feedbacks')
    op.drop_table('commission_structures')
    # ### end Alembic commands ###
