"""hr phase 1: attendance, leave, approval, payroll ext, audit, advances

Revision ID: dbceffd80f23
Revises: ac9de03e7289
Create Date: 2026-07-15 01:20:22.187794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbceffd80f23'
down_revision: Union[str, Sequence[str], None] = 'ac9de03e7289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_actor', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('current_approver_id', sa.String(length=36), nullable=True),
    sa.Column('next_approvers_csv', sa.String(length=255), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('acted_via', sa.String(length=20), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('escalated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_approver_status', ['current_approver_id', 'status'], unique=False)
        batch_op.create_index('ix_approvals_requester', ['requester_id', 'created_at'], unique=False)
        batch_op.create_index('ix_approvals_status', ['status'], unique=False)
        batch_op.create_index('ix_approvals_type_ref', ['type', 'ref_id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('annual_total', sa.Float(), nullable=False),
    sa.Column('annual_used', sa.Float(), nullable=False),
    sa.Column('sick_used', sa.Float(), nullable=False),
    sa.Column('unpaid_used', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index('ix_leave_balances_user_year', ['user_id', 'year'], unique=True)

    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index('ix_leave_requests_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_leave_requests_status', ['status'], unique=False)
        batch_op.create_index('ix_leave_requests_user', ['user_id', 'start_date'], unique=False)

    op.create_table('salary_advances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('period_deducted', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.create_index('ix_advances_user_status', ['user_id', 'status'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('check_in_lat', sa.Float(), nullable=True),
    sa.Column('check_in_lng', sa.Float(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.Column('ot_hours', sa.Float(), nullable=False),
    sa.Column('ot_status', sa.String(length=20), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_date', ['work_date'], unique=False)
        batch_op.create_index('ix_attendance_ot_status', ['ot_status'], unique=False)
        batch_op.create_index('ix_attendance_user_date', ['user_id', 'work_date'], unique=True)

    # LƯU Ý: leads.channel/contact_status/survey_* và projects.customer_id thuộc baseline
    # (DB production tạo bằng create_all đã có) — KHÔNG thêm lại ở đây.

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('standard_days', sa.Float(), nullable=False, server_default='22'))
        batch_op.add_column(sa.Column('ot_hours', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ot_pay', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('allowance', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bhxh_employee', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bhxh_company', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pit', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('taxable_income', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('advance_deduction', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('gross_salary', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('salary_grade_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payslip_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_payrolls_user_period', ['user_id', 'period'], unique=True)

    # reflect_args: một số DB cũ có cột resign_date/resigned_by được ALTER tay
    # không khai báo kiểu (declared type rỗng) — ép kiểu để batch copy không vỡ
    with op.batch_alter_table(
        'users', schema=None,
        reflect_args=[
            sa.Column('resign_date', sa.DateTime(), nullable=True),
            sa.Column('resigned_by', sa.String(length=36), nullable=True),
        ],
    ) as batch_op:
        batch_op.add_column(sa.Column('salary_grade_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('dependents_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('delegate_to', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('delegate_until', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_users_salary_grade_id', 'salary_grades', ['salary_grade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_salary_grade_id', type_='foreignkey')
        batch_op.drop_column('delegate_until')
        batch_op.drop_column('delegate_to')
        batch_op.drop_column('dependents_count')
        batch_op.drop_column('salary_grade_id')

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_index('ix_payrolls_user_period')
        batch_op.drop_column('payslip_sent_at')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('salary_grade_id')
        batch_op.drop_column('gross_salary')
        batch_op.drop_column('advance_deduction')
        batch_op.drop_column('taxable_income')
        batch_op.drop_column('pit')
        batch_op.drop_column('bhxh_company')
        batch_op.drop_column('bhxh_employee')
        batch_op.drop_column('allowance')
        batch_op.drop_column('ot_pay')
        batch_op.drop_column('ot_hours')
        batch_op.drop_column('standard_days')
        batch_op.drop_column('work_days')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_user_date')
        batch_op.drop_index('ix_attendance_ot_status')
        batch_op.drop_index('ix_attendance_date')

    op.drop_table('attendance_records')
    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.drop_index('ix_advances_user_status')

    op.drop_table('salary_advances')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_requests_user')
        batch_op.drop_index('ix_leave_requests_status')
        batch_op.drop_index('ix_leave_requests_dates')

    op.drop_table('leave_requests')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_balances_user_year')

    op.drop_table('leave_balances')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_type_ref')
        batch_op.drop_index('ix_approvals_status')
        batch_op.drop_index('ix_approvals_requester')
        batch_op.drop_index('ix_approvals_approver_status')

    op.drop_table('approval_requests')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_actor')
        batch_op.drop_index('ix_audit_action')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
